"""
Space Engine AI Composer

Converts natural language prompts into Space Engine scripts using AI.
"""

from typing import Optional
from config import AI_PROVIDER, OPENAI_API_KEY, ANTHROPIC_API_KEY

# SE Script reference for AI context
SE_SCRIPT_REFERENCE = """
Space Engine Script Reference:

CAMERA COMMANDS:
- Goto { Target "ObjectName" }  // Go to an object
- Select "ObjectName"           // Select an object
- Track                         // Track selected object
- Follow                        // Follow selected object

CAMERA MOVEMENT:
- GotoSurface { Lat 0 Lon 0 Alt 1000 }  // Go to surface position
- GotoPos { Dist 1000 }                  // Set distance from target
- SetFOV 60                              // Field of view in degrees

FLIGHT PATH:
- StartFlightPath
- AddWaypoint { Time 0 Pos (x,y,z) Rot (x,y,z,w) }
- PlayFlightPath

TIME:
- SetTime { Date "2025-01-01" Time "12:00:00" }
- SetTimeRate 1                 // 1 = real-time, 1000 = fast forward

RECORDING:
- StartRecording { Width 3840 Height 2160 FPS 30 Codec "x264" }
- StopRecording

RENDERING:
- SetExposure 1.0
- SetBloom 0.5
- SetHDR true

COMMON OBJECTS:
- "Milky Way/Sagittarius A*"    // Supermassive black hole
- "Milky Way/Sun"               // Our sun
- "Andromeda"                   // Andromeda galaxy
- "Milky Way/Asteroid Belt"     // Main asteroid belt
"""

SCENE_TEMPLATES = {
    'black_hole': """
// Black Hole - Event Horizon Approach
// Generated by Space Engine AI

// Navigate to Sagittarius A* (Milky Way's supermassive black hole)
Select "Milky Way/Sagittarius A*"
Goto {{ Target "Milky Way/Sagittarius A*" }}

// Position camera at safe viewing distance
GotoPos {{ Dist {distance}e9 }}  // {distance} billion km
SetFOV 45

// Enable cinematic rendering
SetExposure 1.2
SetBloom 0.3
SetHDR true

// Create slow approach flight path
StartFlightPath
AddWaypoint {{ Time 0 Dist {distance}e9 }}
AddWaypoint {{ Time {duration} Dist {end_distance}e9 }}
PlayFlightPath

// Start recording
StartRecording {{ Width 3840 Height 2160 FPS 30 Duration {duration} }}
""",
    
    'asteroid_belt': """
// Asteroid Belt - Drifting Through the Void
// Generated by Space Engine AI

// Navigate to main asteroid belt
Select "Milky Way/Sun"
Goto {{ Target "Milky Way/Sun" }}

// Position in asteroid belt (2.5 AU from Sun)
GotoPos {{ Dist 375e6 }}  // 375 million km (2.5 AU)
SetFOV 60

// Enable dust and particles
SetExposure 1.0
SetBloom 0.2
SetHDR true

// Slow drift path through belt
StartFlightPath
AddWaypoint {{ Time 0 Pos (375e6, 0, 0) }}
AddWaypoint {{ Time {duration} Pos (380e6, 5e6, 2e6) }}
PlayFlightPath

// Start recording
StartRecording {{ Width 3840 Height 2160 FPS 30 Duration {duration} }}
""",
    
    'galaxy_collision': """
// Galaxy Collision - Cosmic Dance
// Generated by Space Engine AI

// Navigate to Andromeda approach scenario
Select "Andromeda"
Goto {{ Target "Andromeda" }}

// Position for wide view of both galaxies
GotoPos {{ Dist 2.5e6 }}  // 2.5 million light years
SetFOV 90

// Enable galaxy rendering
SetExposure 1.5
SetBloom 0.4
SetHDR true

// Set time rate to show collision (millions of years per second)
SetTimeRate 1e13

// Orbit around collision point
StartFlightPath
AddWaypoint {{ Time 0 Rot (0, 0, 0, 1) }}
AddWaypoint {{ Time {duration} Rot (0, 0.707, 0, 0.707) }}
PlayFlightPath

// Start recording
StartRecording {{ Width 3840 Height 2160 FPS 30 Duration {duration} }}
"""
}


class AIComposer:
    """Converts natural language to Space Engine scripts"""
    
    def __init__(self):
        self.provider = AI_PROVIDER
        self.client = self._init_client()
    
    def _init_client(self):
        """Initialize AI client based on provider"""
        if self.provider == "openai" and OPENAI_API_KEY:
            from openai import OpenAI
            return OpenAI(api_key=OPENAI_API_KEY)
        elif self.provider == "anthropic" and ANTHROPIC_API_KEY:
            from anthropic import Anthropic
            return Anthropic(api_key=ANTHROPIC_API_KEY)
        return None
    
    def from_template(self, template_name: str, duration: int = 600, **kwargs) -> str:
        """Generate SE Script from a pre-defined template"""
        if template_name not in SCENE_TEMPLATES:
            raise ValueError(f"Unknown template: {template_name}")
        
        template = SCENE_TEMPLATES[template_name]
        
        # Default parameters per template
        params = {
            'duration': duration,
            'distance': 100,        # Starting distance
            'end_distance': 10,     # Ending distance (for approach shots)
        }
        params.update(kwargs)
        
        return template.format(**params)
    
    def from_prompt(self, prompt: str, duration: int = 600) -> str:
        """Generate SE Script from natural language using AI"""
        if not self.client:
            raise RuntimeError("No AI client configured. Set OPENAI_API_KEY or ANTHROPIC_API_KEY")
        
        system_prompt = f"""You are a Space Engine script generator. Convert the user's natural language 
description into a valid Space Engine script.

{SE_SCRIPT_REFERENCE}

Guidelines:
1. Always include camera setup (position, FOV)
2. Include rendering settings for cinematic quality
3. Create smooth flight paths for camera movement
4. Include recording command at the end
5. Add comments explaining each section
6. Target duration: {duration} seconds

Output ONLY the SE Script, no explanations."""

        if self.provider == "openai":
            response = self.client.chat.completions.create(
                model="gpt-4-turbo-preview",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7
            )
            return response.choices[0].message.content
        
        elif self.provider == "anthropic":
            response = self.client.messages.create(
                model="claude-3-opus-20240229",
                max_tokens=2000,
                system=system_prompt,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            return response.content[0].text
        
        raise RuntimeError(f"Unknown provider: {self.provider}")
    
    def enhance_script(self, script: str, enhancements: list[str]) -> str:
        """Use AI to enhance an existing script with additional features"""
        if not self.client:
            return script
        
        prompt = f"""Enhance this Space Engine script with the following features:
{chr(10).join(f'- {e}' for e in enhancements)}

Original script:
{script}

Output ONLY the enhanced SE Script."""

        return self.from_prompt(prompt)


if __name__ == "__main__":
    # Test template generation
    composer = AIComposer()
    
    print("=== Black Hole Template ===")
    print(composer.from_template('black_hole', duration=300))
    
    print("\n=== Asteroid Belt Template ===")
    print(composer.from_template('asteroid_belt', duration=600))
